### ISSUE TITLE
Implement control loop for Watcher CRs on kcp

### ISSUE THREAD

**Issue by adityabhatia** [kyma-project/kyma-watcher#28]
Implement two seperate control loops for the KCP-Watcher-Operator

We will have one ConfigMap per Watcher CR  (and one Watcher CR per operator) on the KCP. This ConfigMap includes all Kymas which make use of this operator. It will later on be used for reconciling the Watcher on all Kymas.

AC: 

- [ ] Optional (Not decided yet):
     - Implement State handling based on Watcher installation on target cluster

**Comment by jeremyharisch** [comment]
Duplicate all sub-tasks are no tracking #15

**Comment by jeremyharisch** [comment]
Duplicate all sub-tasks are no tracking #15
